# Example config file for `mlem` executable

# A file like this one must be passed as the first argument to `mlem`
#
# TODO: generate output filename from metadata

# ================================================================================
# Mandatory section: describes which LORs should be used during the reconstruction
#
# NB, tilde expansion in filenames is not supported. TODO: consider whether it should be
#
[input]

file = "/home/jacek/rust/petalo/junk.h5"

#file = "/home/jacek/data/jaszczak/lors/6-udlx-s4r4b1-vacbody-nosteel-dz2m-LYSO10mm-discrete-r350-dr10-dz6-da6-adjust-random-z-phi-1500Mevents.h5"
#file = "/home/jacek/data/jaszczak/lors/6-udlx-s4r4b1-H2Obody-nosteel-dz2m-LYSO10mm-discrete-r350-dr10-dz6-da6-adjust-random-z-phi-7500Mevents.h5"
#file = "/home/jacek/data/jaszczak/lors/6-udlx-s4r4b1-H2Obody-nosteel-dz2m-CsI20mm-discrete-r350-dr20-dz6-da6-adjust-random-z-phi-7500Mevents.h5"
#file = "/home/jacek/data/jaszczak/lors/6-udlx-s4r4b1-H2Obody-nosteel-dz2m-LXe40mm-discrete-r350-dr40-dz6-da6-adjust-random-z-phi-7500Mevents.h5"

dataset = "reco_info/lors"

# Optional: event filtering by energy
#
#energy.min = 483  # for  5% FWHM
#energy.min = 429  # for 15% FWHM

# energy.max = 600

# Optional: event filtering by charge
#
# charge.min = 123
# charge.max = 456

# Optional: event selection by position in input file
#
# events.min = 100_000_000  #      inclusive  lower limit
# events.max = 200_000_000  # NB: *exclusive* upper limit


# ================================================================================
# Mandatory section: MLEM/OSEM iterations/subsets
#
[iterations]
number  = 4
subsets = 20


# ================================================================================
# Mandatory section: Size of the Field of View (FOV)
#
[fov]

nvoxels = [ 78     ,  78     ,    72    ]
size    = ["234 mm", "234 mm",  "216 mm"]

# ================================================================================
# Optional section: Enable use of Time of Flight (TOF) information

# [tof]
# sigma = "200 ps"
# cutoff = 3       # Ignore voxels whose centre lies more than `cutoff` sigmas from TOF peak


# ================================================================================
# Optional section: Enable annetuation correction
#
# NB: tilde-expansion in filename not supported!

# [attenuation_correction]

# # sensitivity_image = "/home/jacek/data/jaszczak/corr/sensitivity-78x78x72-3-mm-cubed-voxels/discrete-adjust-random-siddon-l300mm-rmin350mm-dr10mm-dz6mm-da6mm-0.095-cm2-per-g.raw"
# # sensitivity_image = "/home/jacek/data/jaszczak/corr/sensitivity-78x78x72-3-mm-cubed-voxels/discrete-adjust-random-siddon-l300mm-rmin350mm-dr20mm-dz6mm-da6mm-0.095-cm2-per-g.raw"
# # sensitivity_image = "/home/jacek/data/jaszczak/corr/sensitivity-78x78x72-3-mm-cubed-voxels/discrete-adjust-random-siddon-l300mm-rmin350mm-dr40mm-dz6mm-da6mm-0.095-cm2-per-g.raw"
# # sensitivity_image = "/home/jacek/data/jaszczak/corr/sensitivity-78x78x72-3-mm-cubed-voxels/discrete-adjust-random-siddon-l1000mm-rmin350mm-dr10mm-dz6mm-da6mm-0.095-cm2-per-g.raw"
# # sensitivity_image = "/home/jacek/data/jaszczak/corr/sensitivity-78x78x72-3-mm-cubed-voxels/discrete-adjust-random-siddon-l1000mm-rmin350mm-dr20mm-dz6mm-da6mm-0.095-cm2-per-g.raw"
# # sensitivity_image = "/home/jacek/data/jaszczak/corr/sensitivity-78x78x72-3-mm-cubed-voxels/discrete-adjust-random-siddon-l1000mm-rmin350mm-dr40mm-dz6mm-da6mm-0.095-cm2-per-g.raw"
# # sensitivity_image = "/home/jacek/data/jaszczak/corr/sensitivity-78x78x72-3-mm-cubed-voxels/discrete-adjust-random-siddon-l2000mm-rmin350mm-dr10mm-dz6mm-da6mm-0.095-cm2-per-g.raw"
# sensitivity_image = "/home/jacek/data/jaszczak/corr/sensitivity-78x78x72-3-mm-cubed-voxels/discrete-adjust-random-siddon-l2000mm-rmin350mm-dr20mm-dz6mm-da6mm-0.095-cm2-per-g.raw"
# # sensitivity_image = "/home/jacek/data/jaszczak/corr/sensitivity-78x78x72-3-mm-cubed-voxels/discrete-adjust-random-siddon-l2000mm-rmin350mm-dr40mm-dz6mm-da6mm-0.095-cm2-per-g.raw"

# ================================================================================
# Optional section: Enable scatter correction

# [scatter_correction]

# phi.bins =   40

# r.bins  =    40
# r.max   =  "120 mm"

# # dt.bins =    10
# # dt.max  =    "1 ns"

# z.bins   =   30
# z.length = "220 mm"

# dz.bins =   80
# dz.max  = "2000 mm"

# ================================================================================
# Optional section: Enable energy smearing
#
[smear_energy]
fwhm = "15 %"

# ================================================================================
# Optional section: Ignore LORs that would not be detected by shorter detector
#
[detector_full_axial_length]
dz = "2000 mm"
